---
title: "<h1 style='text-align: center;'>Teaching Interests</h1>" #"Teaching"

---

<!-- <div style="text-align: center;">
# Teaching Interests
</div> -->

<div style="text-align: center;">
Marketing Analytics, Marketing Strategy, Digital Selling, Digital Marketing, AI in Marketing
</div>

<div style="text-align: center;">
# Teaching Experience
</div>

## Instructor

MARK3338: Introduction to Marketing Analytics (Undergraduate Elective), Summer 2025

MARK3338: Introduction to Marketing Analytics (Undergraduate Elective), Summer 2024

- Instructor rating: 4.64/5.0 (school average: 4.45/5.0)

Selected comments from student evaluations:

- "This is one of the best courses I have ever taken while here at UH. I was able to fully get understand what was being taught."

- "The overall covering of excel in the course went well. It was the best way to learn the excel commands..."

- "The professor explained topics well and guided us through in class exercises thoroughly. Professor provided much feedback."

- "The professor was great, helpful and attentive to students. I would highly suggest this professor to anyone taking Marketing Analytics."

## Teaching Assistant

MARK 3337: Professional Selling (Undergraduate Elective)
